### ISSUE TITLE
Esko SC Script issue

### ISSUE THREAD

**Issue by saco-ekso** [tuxfre/esko-SC-scripts#10]
# Esko SC Script issue
## Affected script
- Name: List View Highlighter
- Version: 19
## OS
- Name: Windows
- Version: 7 Pro SP1
- Language: US English
## Browser
- Name: Firefox
- version: 45.01
- language (if different from OS):
## Short summary if your issue

Script is not working. Possibly the wrong date format?
## Steps to reproduce the issue

See screen shot below for view 
![date format](https://cloud.githubusercontent.com/assets/18007911/13953244/55c41600-f011-11e5-8e06-51cf1f2f0bae.png)
setting used
## Other details:

**Don't hesitate to include details and screenshots.**

---

@tuxfre

**Comment by tuxfre** [comment]
hi @saco-ekso,

Does you capture show all your columns?
Because, if yes, you are lacking at least one required column for it to work (Contract Status).
Also, I see only waiting logs, the highlighter works only for "new" or "pending" cases.

A simple test to make sur if it's the date or not would be to use one of the default views provided by @korinapieters (I'm not sure how they're named for NA). _In theory, we support only the default views, not the custom views_, it would make data extraction too complex.

**Comment by saco-ekso** [comment]
Thanks Benjamin,
I will test this with the default view.
Sam

**Comment by saco-ekso** [comment]
Works with default CS: Support Engineers NA view
