### ISSUE TITLE
Local Links script

### ISSUE THREAD

**Issue by saco-ekso** [tuxfre/esko-SC-scripts#11]
# Esko SC Script issue
## Affected script
- Name: ServiceCloud Local Links
- Version:8
## OS
- Name: Windows
- Version: 7 Pro SP1
- Language: US English
## Browser
- Name: FireFox
- version:45.0.1
- language (if different from OS):
## Short summary if your issue

When I click on one of the links to a job folder a new tab is opened for the job folder but I cannot drag and drop a file into it. Is this how it should work?
## Steps to reproduce the issue

Click on the link
A new tab opens with the directory of the job folder
When I drag a file to this window the file is duplicated in its original location
## Other details:

I have a small movie file that show the issue. I can e-mail it to you. Let me know.

---

@tuxfre

**Comment by tuxfre** [comment]
Hi @saco-ekso,

Using the scripts, the links _should_ open in a Windows Explorer window instead of a new tab in Firefox. That's odd. 
If you want you should be able to upload your movie here, by dropping it on the text box.

In theory, when using Firefox, you need also to add the custom [user.js](https://raw.githubusercontent.com/tuxfre/esko-SC-scripts/master/.resources/user.js) to your profile directory, as described in the Wiki.

Then, after restarting Firefox, this first time you click on a file:// link, it should ask you what to do:
![action window](https://cloud.githubusercontent.com/assets/600530/13671362/d592676a-e6cf-11e5-9cc3-886585437bc5.png)

I remember you seemed to have issues last time, but that after quitting Firefox, you could add the user.js.
Can you check if the user.js is still in your profile folder?

Also, can you maybe go to the [Configuration  Editor for Firefox](https://support.mozilla.org/en-US/kb/about-config-editor-firefox) and search for the value of the following parameters:
1. capability.policy.policynames
2. capability.policy.localfilelinks.sites
3. network.protocol-handler.expose.file 

(a screen capture would be prefect) 

Kind regards,

Benjamin

**Comment by saco-ekso** [comment]
I quit Firefox, deleted the old user.js file, created a new one and started Firefox, tried the link and it did not help.
The movie format is not excepted
Below are the Configuration Editor for Firefox settings you requested
![policies1](https://cloud.githubusercontent.com/assets/18007911/14184065/53fe00ec-f741-11e5-837d-b648a997c162.png)
![policies2](https://cloud.githubusercontent.com/assets/18007911/14184064/53fd4468-f741-11e5-8403-14dfbe639941.png)
Thanks,
Sam

**Comment by saco-ekso** [comment]
Here's the movie. You will need to change the extension from .jpg to .mp4

![job folder link](https://cloud.githubusercontent.com/assets/18007911/14184137/b750faa0-f741-11e5-9bef-aa5833bf0a5f.jpg)

**Comment by tuxfre** [comment]
Hi Sam,

I'll have a look at this tomorrow morning (it's already 7pm over here)

Thanks for the movie and captures!

Benjamin

**Comment by saco-ekso** [comment]
Hi Benjamin,

That will be fine.

Have a great evening!

Kind regards,

Sam Cox | Application Support Specialist | Esko

For all support, visit help.esko.comhttp://help.esko.com/

[esko-logo-mail]

**Comment by tuxfre** [comment]
Hi Sam,

Something just crossed my mind, do you do a "normal" left-click, or are you using the "scrollwheel-click" (or any variant such as shift+click, crtl+click) that is meant to open files into a new tab?

I made a small movie that shows the difference between a "standard" left-click (first example in the video) and the "scrollwheel-click" (second example). 

Check https://esko.box.com/click

Kind regards,

Benjamin

**Comment by saco-ekso** [comment]
Hi Benjamin,

I am using the normal left click. I did try all of the other variations and they produce the same result. The morning when I clicked on the link to Mac folders I was presented with the screen to choose an application to open it with. I chose Internet Explorer and it opens the program but get the message below, which I assume is expected.
![mac link](https://cloud.githubusercontent.com/assets/18007911/14206542/beeede3a-f7e1-11e5-9cf0-be186ffa9745.png)

**Comment by tuxfre** [comment]
Hi Sam,

Indeed, it is expected that the mac link doesn't work on PC. But that was a very good test... because I think I may know where the issue comes from. It is possible that in Firefox's preferences, the file:// links are actually associated with Firefox itself instead of the Windows Explorer.

To check that you can go to the "Applications" section of the option panel (you can type [about:preferences#applications](about:preferences#applications) in the address bar, see https://support.mozilla.org/en-US/kb/applications-panel-set-how-firefox-handles-files for more details).

Then search for a line showing file, like in the following capture:
![screen shot 2016-04-01 at 14 20 26](https://cloud.githubusercontent.com/assets/600530/14206673/0d5f9018-f815-11e5-9b55-b12b41312a4c.png)

There, make sure that the action is "Use Windows Explorer".

Kind regards,

Benjamin

**Comment by saco-ekso** [comment]
Success!!! It works great!

Thanx for the help and have a great weekend!

**Comment by tuxfre** [comment]
Very happy to have been able to help you!

I wish you also a very pleasant weekend.

**Comment by saco-ekso** [comment]
Benjamin, 
Can we reopen this. I just noticed the path to the folder is \CC-SW-Problemlog-Gent\CC-SW-Problemlog-Gent. For NA is should be S:\CC-SW-Problemlog-NA

**Comment by tuxfre** [comment]
Hi Sam,

In my opinion, that's another issue ;)

Please open a new log, I'll have a look on monday. 

I'll have to make some setting panel like for Telescope.

Have a nice weekend!

Benjamin
