### ISSUE TITLE
List View Highlighter vs office hours

### ISSUE THREAD

**Issue by andsesko** [tuxfre/esko-SC-scripts#6]
# Esko SC Script issue
## Steps to reproduce the issue: Looking at a couple of issues that were created @ 6:24-6:47 AM, are at 8:33 AM listed grey as having passed the 1h limit, which is in se correct, but I think RT time is only calculated within office hours (8:00-18:00)? Opening the case does indeed still show xx minutes left. Don't know if that's an easy one to fix (keeping into account local time zones)?

Thanks!
Andy
## Other details:

Screenshot:
![listviewhighlighter_workinghours](https://cloud.githubusercontent.com/assets/17767558/13696358/2810bea6-e766-11e5-8aea-9cba7214ec0e.png)

@tuxfre

**Comment by tuxfre** [comment]
Hi @andsesko 

By design it only account the time spent, not the office hours. 
That's a known limitation, it will affect a small part of the logs.

The idea here is to help with the biggest part of the 'bunch' of logs.

Implementing office hours is far from being easy and will only change the situation for a limited set of cases.

If, this is really a showstopper amongst users, then we can discuss that with GN and I can _try_ implementing something.

Kr,

Benjamin

**Comment by andsesko** [comment]
Hi @tuxfre,

Was afraid so. Thanks for confirming.
I can live with it; won't let perfect get in the way of better (yes, it;s definitely an improvement and should indeed cover the vast majority of the cases correctly) ;o) 

Kind Regards,
Andy
